kind: pipeline
name: default

clone:
  git:
    image: plugins/git
    depth: 1

steps:
- name: install
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
    - dotnet restore

- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
    - dotnet test ./Finpe.Test

- name: docker-forno
  image: plugins/docker
  settings:
    repo: tiagodeliberali/finpeapi
    tags: 
      - "forno-${DRONE_COMMIT:0:7}"
      - "forno-latest"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event: push
    branch: [master]