clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  install:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    commands:
      - dotnet restore

  test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    commands:
      - dotnet test ./Finpe.Test

  docker-api:
    image: plugins/docker
    dockerfile: docker/api.Dockerfile
    secrets: [docker_username, docker_password]
    repo: tiagodeliberali/finpeapi
    tag: ["${DRONE_BRANCH}-${DRONE_COMMIT:0:7}", "${DRONE_BRANCH}-latest"]
    build_args:
        - COMMIT=${DRONE_COMMIT:0:7}
    when:
      event: push
      branch: [master, forno]

  docker-front-forno:
    image: plugins/docker
    dockerfile: docker/front.Dockerfile
    secrets: [docker_username, docker_password]
    repo: tiagodeliberali/finpereact
    tag: ["${DRONE_BRANCH}-${DRONE_COMMIT:0:7}", "${DRONE_BRANCH}-latest"]
    build_args:
        - API_URL=https://finpe-api-forno.azurewebsites.net/api/
    when:
      event: push
      branch: [forno]

  docker-front-prod:
    image: plugins/docker
    dockerfile: docker/front.Dockerfile
    secrets: [docker_username, docker_password]
    repo: tiagodeliberali/finpereact
    tag: ["${DRONE_BRANCH}-${DRONE_COMMIT:0:7}", "${DRONE_BRANCH}-latest"]
    build_args:
        - API_URL=https://finpe-api.azurewebsites.net/api/
    when:
      event: push
      branch: [master]
